version: '3.7'

services:
  holidays-backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.docker
  holidays-database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'holidays'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
  holidays-redis:
    image: redis:latest
    ports:
      - 6379:6379
